### ISSUE TITLE
How to get the `test.html` file

### ISSUE THREAD

**Issue by Qianlei112** [PengHaiZhuo/WebViewDemo#1]
https://github.com/PengHaiZhuo/WebViewDemo/blob/804cc82cf7ee49b5109152efe51bda0420736237/app/src/main/java/com/phz/webviewdemo/MainActivity.kt#L44

You need to create a new folder under the asset folder and then move the test.html to the new folder.

**Comment by PengHaiZhuo** [comment]
Files in the asset directory cannot be obtained directly, but can only be copied through the file stream.

**Comment by PengHaiZhuo** [comment]
Thanks,I understand.It would be better
` wb.loadUrl("file:///android_asset/test.html");`
